title : Audrey Le's Research Blog
description: A blog about data privacy and user experience design

baseurl: "" # the subpath of your site, e.g. /blog
url: ""
twitter_username: politicaltones
github_username:  audreyle

markdown: kramdown
paginate: 15
plugins: 
 - jekyll-paginate
permalink: /:year/:month/:title.html
