title : Wall-E - Jekyll
description: 'Audrey Le's Research Blog'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins: [jekyll-gist] [jekyll-paginate]
permalink: /:year/:month/:title.html
